spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/worktime_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080